### ISSUE TITLE
Again, initialisation error, but with App.config

### ISSUE THREAD

**Issue by haf** [mausch/Fuchu#55]
https://ci.appveyor.com/project/haf/logary/build/4.0.7

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$Logary-Adapters-Facade-Tests>.$Program' threw an exception. ---> System.MissingMethodException: Method not found: 'Fuchu.Test Fuchu.Test.NewTestCase(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Core.Unit>)'.
   at Program.tests@73-2.Invoke(Unit unitVar)
   at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@881.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$Logary-Adapters-Facade-Tests>.$Program..cctor()
   --- End of inner exception stack trace ---
   at Program.main(String[] argv)

```

App.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<runtime><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <Paket>True</Paket>
    <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.4.0.0" />
  </dependentAssembly>
</assemblyBinding></runtime></configuration>
```

**Comment by mausch** [comment]
The problem is, `App.config` is not part of `Logary.Adapters.Facade.Tests.fsproj` so the the output dir doesn't have `Logary.Adapters.Facade.Tests.exe.config`

**Comment by haf** [comment]
You're right of course. Thank you for bearing with me.
