### ISSUE TITLE
System.NullReferenceException when building a test in Visual Studio

### ISSUE THREAD

**Issue by justanotheratom** [mausch/Fuchu#58]
------ Discover test started ------
NUnit Adapter 3.7.0.0: Test discovery starting
Assembly contains no NUnit 3.0 tests: C:\Users\sanke\OneDrive\code\github\Algorithms\FSharp\FSharp\bin\Debug\FSharp.exe
NUnit Adapter 3.7.0.0: Test discovery complete
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at Fuchu.Impl.testFromMember@342-1.Invoke(MemberInfo m) in c:\prg\Fuchu\Fuchu\Fuchu.fs:line 343
   at Microsoft.FSharp.Primitives.Basics.List.choose[T,TResult](FSharpFunc`2 f, FSharpList`1 xs)
   at Fuchu.Impl.testFromMember(MemberInfo m) in c:\prg\Fuchu\Fuchu\Fuchu.fs:line 357
   at Fuchu.Impl.testFromType@372-1.Invoke(MemberInfo m) in c:\prg\Fuchu\Fuchu\Fuchu.fs:line 372
   at Microsoft.FSharp.Collections.IEnumerator.choose@205.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fuchu.Impl.testFromType@367.Invoke(Type t) in c:\prg\Fuchu\Fuchu\Fuchu.fs:line 368
   at Microsoft.FSharp.Collections.IEnumerator.choose@205.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fuchu.Impl.testFromAssemblyWithFilter(FSharpFunc`2 typeFilter, Assembly a) in c:\prg\Fuchu\Fuchu\Fuchu.fs:line 378
   at Fuchu.Impl.testFromAssembly@385-1.Invoke(Assembly a) in c:\prg\Fuchu\Fuchu\Fuchu.fs:line 385
   at Discovery.DiscoverProxy.DiscoverTests(String source)
   at Discovery.DiscoverProxy.DiscoverTests(String source)
   at Discovery.Discoverer.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestDiscoverer-DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
========== Discover test finished: 2 found (0:00:00.6280152) ==========

Source Code
========

module MaximizeStockProfit

open System
open NUnit.Framework
open FsUnit
open Fuchu

let maxProfit1 p =
    
    let rec loop minSoFar maxProfitSoFar rest =
        match rest with
        | [] -> maxProfitSoFar
        | h :: t ->
            let newMin =
                if (h < minSoFar) then h else minSoFar
            let newMaxProfit =
                let profit = h - minSoFar
                if (profit > maxProfitSoFar) then profit else maxProfitSoFar
            loop newMin newMaxProfit t

    match p with
    | [] | [_] -> failwith "Not enough datapoints"
    | h :: t -> loop h Int32.MinValue t

[<TestFixture>]
type Tests () =

    [<Test>]
    member x.``Basic Tests`` () =
        [ ([2;3], 1); ([3;2], -1); ([5;3;8;0], 5); ([5;4;3;2;1], -1); ([1;2;3;4;3;2;1], 3) ]
        |> List.iter (fun (i, o) -> maxProfit1 i |> should equal o)

    [<Test>]
    member x.``Negative Tests`` () =
        [ []; [2] ]
        |> List.iter
            (fun (i) ->
                (fun () -> maxProfit1 i |> ignore)
                |> should (throwWithMessage "Not enough datapoints") typeof<Exception>)

[<Tests>]
let tests =

    let expect input output _ =
        maxProfit1 input |> should equal output

    let basicTest i (input, output) =
        testCase (sprintf "%i" i) <| expect input output

    let shouldFail input _ =
        maxProfit1 input |> should (throwWithMessage "Not enough datapoints") typeof<Exception>

    let negativeTest i input =
        testCase (sprintf "%i" i) <| shouldFail input

    testList "MaximizeStockProfit" [
        testList "Basic" (
            [ ([2;3], 1); ([3;2], -1); ([5;3;8;0], 5); ([5;4;3;2;1], -1); ([1;2;3;4;3;2;1], 3) ]
            |> List.mapi basicTest
        )
        testList "Negative" (
            [ []; [2] ]
            |> List.mapi negativeTest
        )
    ]

**Comment by justanotheratom** [comment]
Turns out, I did not have an [<EntryPoint>] function.
